### ISSUE TITLE
Static binary release for 0.7.1 possible?

### ISSUE THREAD

**Issue by webframp** [channable/vaultenv#43] opened 2018-05-03 20:23 UTC
Hi! 👋 

I'm not very familiar with the current state of haskell builds with stack, but was curious if you think it's possible to get a static 64bit linux binary on the releases?

Or maybe you know pointers/current blockers for doing this myself? Thanks!

**Comment by webframp** [comment] 2018-05-04 13:41
My reason for a static binary is using vaultenv in docker containers. For the smallest possible container I'd like to be able to create a layer using `FROM scratch` or at least alpine linux, instead of having the external lib dependencies and a larger base container image.

**Comment by duijf** [comment] 2018-05-04 14:40
Alpine isn't officially supported by Stack yet https://github.com/commercialhaskell/stack/issues/2387, but reportedly people have gotten this to work for GHC 8.0.2. Vaultenv uses GHC 8.2 through stack, but it still compiles successfully if you change the resolver to `lts-9.20` in `stack.yaml`.

The foundation Haskell library builds against `musl`: https://github.com/haskell-foundation/foundation/issues/393 so building Haskell on Alpine against `musl` can be done. Don't know about `vaultenv`, though, but it's worth a shot

Some instructions that I found on this:

 - https://www.reddit.com/r/haskell/comments/5lk33p/struggling_building_a_static_binary_for_aws/
 - https://gist.github.com/erebe/9611b2c8f1d26cc91cc3fb33bbae0eb9

**Comment by naushadh** [comment] 2018-05-09 07:52
@webframp check out https://github.com/naushadh/hello-world

**Comment by webframp** [comment] 2018-05-18 03:32
Thanks for the tip @naushadh 

I experimented but the resolver is different between the hello-world example and vaultenv, no success yet but I'll keep at it as my time allows

**Comment by naushadh** [comment] 2018-05-18 07:11
@webframp perhaps try bumping down the `vaultenv` resolver to match what's in `hello-world` (9.21)? @duijf already appears to have [had success with resolver 9.2](https://github.com/channable/vaultenv/issues/43#issuecomment-386622859).

Once https://github.com/alpinelinux/aports/pull/4255 gets merged, newer resolver should be possible in the alpine docker setup.

**Comment by ruuda** [comment] 2018-05-18 21:02
I was able to build a static binary like so (based on [this blog post](https://vaibhavsagar.com/blog/2018/01/03/static-haskell-nix/)):

```
$ cabal2nix --shell . > default.nix
```
Then insert the following lines:
```nix
  enableSharedExecutables = false;
  enableSharedLibraries = false;
  configureFlags = [
    "--ghc-option=-optl=-static"
    "--ghc-option=-optl=-pthread"
    "--ghc-option=-optl=-L${pkgs.gmp6.override { withStatic = true; }}/lib"
    "--ghc-option=-optl=-L${pkgs.zlib.static}/lib"
    "--ghc-option=-optl=-L${pkgs.glibc.static}/lib"
  ];
```
Then build the binary:
```
$ nix build
$ file result/bin/vaultenv
result/bin/vaultenv: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, stripped
```

**Comment by ruuda** [comment] 2018-05-22 07:02
Good point @arianvp.

**Comment by nh2** [comment] 2018-06-14 12:59
Issue title:

> Static binary release for 0.7.1 possible?

@webframp Do you mean `1.7.1`?

**Comment by nh2** [comment] 2018-06-14 20:06
> I was able to build a static binary like so (based on this blog post):

@ruuda I tuned the idea of that blog post further, so that you can link fully statically with `musl` instead of `glibc` ([glibc doesn't really support fully static linking](https://sourceware.org/glibc/wiki/FAQ#Even_statically_linked_programs_need_some_shared_libraries_which_is_not_acceptable_for_me.__What_can_I_do.3F)):

https://github.com/nh2/static-haskell-nix

It can now build executables with many dependencies, such as `stack` (there's an example in the repo). You may be able to adapt this approach to build whatever you would like fully statically.

**Comment by agix** [comment] 2019-05-15 07:42
According to the previous link and poking around on the internet, I successfully built a statically linked vaultenv following this simple process

`git clone https://github.com/channable/vaultenv`

edit `package.yaml` to add `    ld-options: -static` in `executables`

```
executables:
  vaultenv:
    main: Main.hs
    source-dirs: app
    ld-options: -static
    dependencies:
      - vaultenv
```

`docker run --rm -v $(pwd)/vaultenv:/app -it fpco/stack-build:lts-12.9 /bin/bash`

with `lts-12.9` equals to the one in `stack.yaml`

In the docker, go to `/app` and run the stack install

`stack clean; stack install --split-objs --ghc-options="-fPIC -fllvm"`

```
root@47eb6446173d:~# file /root/.local/bin/vaultenv 
/root/.local/bin/vaultenv: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=30bd59a4f83818d7ac1a26c08a09e043a2a4e9cd, stripped
```

[vaultenv.zip](https://github.com/channable/vaultenv/files/3181432/vaultenv.zip)

**Comment by nh2** [comment] 2019-05-15 18:46
@agix Did you ensure that you don't link statically against glibc though?

glibc is the default libc on most Linux distributions, so if you just add `-static` flags, you are likely to use that, which creates a high probability that your program will crash at run time, like [in this example](https://github.com/nh2/static-haskell-nix/issues/17).

The easiest way to get static executables is to add the project to [Stackage](https://www.stackage.org/) because [static-haskell-nix](https://github.com/nh2/static-haskell-nix) can already create statically linked executables out of the box for most programs on Stackage.

**Comment by agix** [comment] 2019-05-29 14:25
Hi, yes I read some function may not work properly. 
At least it does the job for me and I can now use vaultenv in my docker images... Waiting for a better method.

**Comment by ruuda** [comment] 2019-08-02 14:46
I was following along the developments in https://github.com/NixOS/nixpkgs/issues/43795; I think we should give `static-haskell-nix` a try, and if it works, make it the default at least for the releases we upload here. It would solve compatibility issues [like this one](https://github.com/channable/vaultenv/issues/69#issuecomment-515013756).

**Comment by duijf** [comment] 2019-08-10 15:09
I've started work on fully static binaries with Nix and have a working PoC in the [`nix-build`](https://github.com/channable/vaultenv/tree/nix-build) branch.

The binaries currently aren't fit for distribution, as they statically against `libgmp`, which is a LGPL software. I hope to get a working build with `integer-simple` as well

**Comment by nh2** [comment] 2019-08-10 20:50
@duijf Regarding https://github.com/channable/vaultenv/commit/1cce569f4bd8c1ede673fc4a4076507192ce31ea, did you see that you can also easily static-nixify stack projects, see https://github.com/nh2/static-haskell-nix/tree/master/static-stack2nix-builder-example  ?

**Comment by ruuda** [comment] 2019-08-10 21:04
@nh2, I tried that in 073511179c171864b2b589c85ca8e989733e86d9, but I ran into the following error:

```
...
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.4.4 cabal://zstd-0.1.0.0
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.4.4 cabal://zot-0.0.3
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.4.4 cabal://ztail-1.2.0.2
stack2nix: /tmp/stack2nix-output-dir.yfkiFc11m8/stack2nix-output.nix: commitBuffer: invalid argument (invalid character)
```

I can reproduce it reliably, but I haven’t looked more closely into what is going on.

**Comment by nh2** [comment] 2019-08-10 21:35
@ruuda Ah, another instance of the horrible "`Handle` encoding guessing` problem. Try the suggestion in https://github.com/input-output-hk/stack2nix/issues/150#issuecomment-443221773, `LANG=en_US.utf8`, as a workaround.

Overall I expect that using `stack2nix` will be a much better working experience for most projects than pinning your version of packages to what nixpkgs has; so I think this is worth working out.

**Comment by nh2** [comment] 2019-08-10 21:36
@ruuda Oh and of course please tell me what `echo $LANG` is for you normally, so I can see if I can reproduce it.

**Comment by ruuda** [comment] 2019-08-10 22:11
I use `LANG=en_GB.utf8`. Setting `LANG=en_US.utf8` when running `...-stack2nix-and-build-script.sh` does not help, nor does adding `export LANG=en_US.utf8` to that generated script. I also tried adding it deeper, just before the `stack2nix` call [here](https://github.com/ruuda/static-haskell-nix/commit/0f6e5750e5adef4c6063205514c47ed96db0610e), but that did not help either.

**Comment by duijf** [comment] 2019-08-10 22:15
> Overall I expect that using stack2nix will be a much better working experience for most projects than pinning your version of packages to what nixpkgs has; so I think this is worth working out.

I don't have much experience with either approach. What are the pros and cons in your opinion?

> `LANG=en_US.utf8`, as a workaround.

I have `LANG=en_US.utf8` set. 

```
~/repos/channable/vaultenv static
❯ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

~/repos/channable/vaultenv static
❯ git rev-parse HEAD
073511179c171864b2b589c85ca8e989733e86d9

~/repos/channable/vaultenv static
❯ nix-build --no-link -A fullBuildScript                                   
/nix/store/iwkf1hyr8iqcskfb10d54pagvpkiisxv-stack2nix-and-build-script.sh

~/repos/channable/vaultenv static
❯ /nix/store/iwkf1hyr8iqcskfb10d54pagvpkiisxv-stack2nix-and-build-script.sh
+ /nix/store/0acd2zbljgc38f50xwfhhsc5fb6l5xmg-stack2nix-0.2.2/bin/stack2nix /home/duijf/repos/channable/vaultenv --stack-yaml stack.yaml --hackage-snapshot 2019-08-02T00:00:00Z -o /tmp/stack2nix-output-dir.tx4bkmDm8M/stack2nix-output.nix
/nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Ensuring git version is >= 2 ...
Ensuring cabal version is >= 2 ...

+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.4.4 cabal://ALUT-2.4.0.2
[...]
+ cabal2nix --subpath . --system x86_64-linux --compiler ghc-8.4.4 cabal://ztail-1.2.0.2
stack2nix: /tmp/stack2nix-output-dir.tx4bkmDm8M/stack2nix-output.nix: commitBuffer: invalid argument (invalid character)
```

I guess there is something to the warning about failing to set `LC_ALL`?

**Comment by nh2** [comment] 2019-08-10 22:25
> I don't have much experience with either approach. What are the pros and cons in your opinion?

With stack2nix you can continue using stack and `stack.yaml`, thus being able to switch the Stackage version at will and use different dependencies much more freely than with nixpkgs (which has only 1 Stackage version in it at any given point in time).

**Comment by nh2** [comment] 2019-08-15 22:07
> `commitBuffer: invalid argument (invalid character)`

Ah, I see. I think we're using a too old version, thus missing this fix https://github.com/input-output-hk/stack2nix/commit/cb05818ef8b58899f15641f50cb04e5473b4f9b0 that was released with `stack2nix` 0.2.3.

**Comment by duijf** [comment] 2019-08-16 09:04
@nh2 I wanted to say thank you for all the effort you're putting into static Haskell builds and the help you've given us so far on this one :)

I'll try out the new changes in `static-haskell-nix` on `vaultenv` soon!

**Closed** 2019-10-14 11:18 UTC

**Comment by duijf** [comment] 2019-10-14 14:03
With https://github.com/channable/vaultenv/pull/82 this is fixed. We'll upload a static binary for vaultenv `0.11.0` :)
